// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: order.proto

package apiContracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_PENDING   OrderStatus = 0
	OrderStatus_ORDER_PAID      OrderStatus = 1
	OrderStatus_ORDER_SHIPPED   OrderStatus = 2
	OrderStatus_ORDER_DELIVERED OrderStatus = 3
	OrderStatus_ORDER_CANCELLED OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_PENDING",
		1: "ORDER_PAID",
		2: "ORDER_SHIPPED",
		3: "ORDER_DELIVERED",
		4: "ORDER_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_PENDING":   0,
		"ORDER_PAID":      1,
		"ORDER_SHIPPED":   2,
		"ORDER_DELIVERED": 3,
		"ORDER_CANCELLED": 4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type PaymantMethod int32

const (
	PaymantMethod_PAYMENT_UNSPECIFIED    PaymantMethod = 0
	PaymantMethod_PAYMENT_CARD           PaymantMethod = 1
	PaymantMethod_PAYMENT_BANK_TRANCSFER PaymantMethod = 2
)

// Enum value maps for PaymantMethod.
var (
	PaymantMethod_name = map[int32]string{
		0: "PAYMENT_UNSPECIFIED",
		1: "PAYMENT_CARD",
		2: "PAYMENT_BANK_TRANCSFER",
	}
	PaymantMethod_value = map[string]int32{
		"PAYMENT_UNSPECIFIED":    0,
		"PAYMENT_CARD":           1,
		"PAYMENT_BANK_TRANCSFER": 2,
	}
)

func (x PaymantMethod) Enum() *PaymantMethod {
	p := new(PaymantMethod)
	*p = x
	return p
}

func (x PaymantMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymantMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (PaymantMethod) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x PaymantMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymantMethod.Descriptor instead.
func (PaymantMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type Discount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to DiscountSpec:
	//
	//	*Discount_Percent
	//	*Discount_Fixed
	DiscountSpec  isDiscount_DiscountSpec `protobuf_oneof:"discount_spec"`
	DiscountCode  string                  `protobuf:"bytes,3,opt,name=discount_code,json=discountCode,proto3" json:"discount_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discount) Reset() {
	*x = Discount{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discount) ProtoMessage() {}

func (x *Discount) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discount.ProtoReflect.Descriptor instead.
func (*Discount) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Discount) GetDiscountSpec() isDiscount_DiscountSpec {
	if x != nil {
		return x.DiscountSpec
	}
	return nil
}

func (x *Discount) GetPercent() *PercentDiscount {
	if x != nil {
		if x, ok := x.DiscountSpec.(*Discount_Percent); ok {
			return x.Percent
		}
	}
	return nil
}

func (x *Discount) GetFixed() *FixedAmountDiscount {
	if x != nil {
		if x, ok := x.DiscountSpec.(*Discount_Fixed); ok {
			return x.Fixed
		}
	}
	return nil
}

func (x *Discount) GetDiscountCode() string {
	if x != nil {
		return x.DiscountCode
	}
	return ""
}

type isDiscount_DiscountSpec interface {
	isDiscount_DiscountSpec()
}

type Discount_Percent struct {
	Percent *PercentDiscount `protobuf:"bytes,1,opt,name=percent,proto3,oneof"`
}

type Discount_Fixed struct {
	Fixed *FixedAmountDiscount `protobuf:"bytes,2,opt,name=fixed,proto3,oneof"`
}

func (*Discount_Percent) isDiscount_DiscountSpec() {}

func (*Discount_Fixed) isDiscount_DiscountSpec() {}

type PercentDiscount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    int32                  `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PercentDiscount) Reset() {
	*x = PercentDiscount{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PercentDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentDiscount) ProtoMessage() {}

func (x *PercentDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentDiscount.ProtoReflect.Descriptor instead.
func (*PercentDiscount) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *PercentDiscount) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type FixedAmountDiscount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedAmountDiscount) Reset() {
	*x = FixedAmountDiscount{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedAmountDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedAmountDiscount) ProtoMessage() {}

func (x *FixedAmountDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedAmountDiscount.ProtoReflect.Descriptor instead.
func (*FixedAmountDiscount) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *FixedAmountDiscount) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	ItemDiscount  *Discount              `protobuf:"bytes,5,opt,name=item_discount,json=itemDiscount,proto3" json:"item_discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetItemDiscount() *Discount {
	if x != nil {
		return x.ItemDiscount
	}
	return nil
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal        float64                `protobuf:"fixed64,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	TotalDiscounts  float64                `protobuf:"fixed64,12,opt,name=total_discounts,json=totalDiscounts,proto3" json:"total_discounts,omitempty"`
	ShippingFee     float64                `protobuf:"fixed64,13,opt,name=shipping_fee,json=shippingFee,proto3" json:"shipping_fee,omitempty"`
	TaxAmount       float64                `protobuf:"fixed64,14,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	GrandTotal      float64                `protobuf:"fixed64,15,opt,name=grand_total,json=grandTotal,proto3" json:"grand_total,omitempty"`
	Status          OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=ecommerce.OrderStatus" json:"status,omitempty"`
	PaymentMethod   PaymantMethod          `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=ecommerce.PaymantMethod" json:"payment_method,omitempty"`
	OrderDiscount   *Discount              `protobuf:"bytes,11,opt,name=order_discount,json=orderDiscount,proto3" json:"order_discount,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,9,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Notes           string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Order) GetTotalDiscounts() float64 {
	if x != nil {
		return x.TotalDiscounts
	}
	return 0
}

func (x *Order) GetShippingFee() float64 {
	if x != nil {
		return x.ShippingFee
	}
	return 0
}

func (x *Order) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *Order) GetGrandTotal() float64 {
	if x != nil {
		return x.GrandTotal
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_PENDING
}

func (x *Order) GetPaymentMethod() PaymantMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymantMethod_PAYMENT_UNSPECIFIED
}

func (x *Order) GetOrderDiscount() *Discount {
	if x != nil {
		return x.OrderDiscount
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *Order) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CustomerId      string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items           []*OrderItemRequest    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	PaymentMethod   PaymantMethod          `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3,enum=ecommerce.PaymantMethod" json:"payment_method,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Notes           string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetPaymentMethod() PaymantMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymantMethod_PAYMENT_UNSPECIFIED
}

func (x *CreateOrderRequest) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type OrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemRequest) Reset() {
	*x = OrderItemRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemRequest) ProtoMessage() {}

func (x *OrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemRequest.ProtoReflect.Descriptor instead.
func (*OrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DiscountAmount int32                  `protobuf:"varint,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Status         OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=ecommerce.OrderStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateOrderResponse) GetDiscountAmount() int32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CreateOrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_PENDING
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus     OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=ecommerce.OrderStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_PENDING
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateOrderStatusResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=ecommerce.OrderStatus" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *ListOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_PENDING
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type SupportMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportMessage) Reset() {
	*x = SupportMessage{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportMessage) ProtoMessage() {}

func (x *SupportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportMessage.ProtoReflect.Descriptor instead.
func (*SupportMessage) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *SupportMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SupportMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SupportMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\tecommerce\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\bDiscount\x126\n" +
	"\apercent\x18\x01 \x01(\v2\x1a.ecommerce.PercentDiscountH\x00R\apercent\x126\n" +
	"\x05fixed\x18\x02 \x01(\v2\x1e.ecommerce.FixedAmountDiscountH\x00R\x05fixed\x12#\n" +
	"\rdiscount_code\x18\x03 \x01(\tR\fdiscountCodeB\x0f\n" +
	"\rdiscount_spec\"7\n" +
	"\x0fPercentDiscount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x05R\n" +
	"percentageJ\x04\b\x02\x10\v\"3\n" +
	"\x13FixedAmountDiscount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amountJ\x04\b\x02\x10\v\"\xc2\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x128\n" +
	"\ritem_discount\x18\x05 \x01(\v2\x13.ecommerce.DiscountR\fitemDiscount\"\xfb\x04\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.ecommerce.OrderItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x01R\bsubtotal\x12'\n" +
	"\x0ftotal_discounts\x18\f \x01(\x01R\x0etotalDiscounts\x12!\n" +
	"\fshipping_fee\x18\r \x01(\x01R\vshippingFee\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\x0e \x01(\x01R\ttaxAmount\x12\x1f\n" +
	"\vgrand_total\x18\x0f \x01(\x01R\n" +
	"grandTotal\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.ecommerce.OrderStatusR\x06status\x12?\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x18.ecommerce.PaymantMethodR\rpaymentMethod\x12:\n" +
	"\x0eorder_discount\x18\v \x01(\v2\x13.ecommerce.DiscountR\rorderDiscount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x10shipping_address\x18\t \x01(\tR\x0fshippingAddress\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\"\xea\x01\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.ecommerce.OrderItemRequestR\x05items\x12?\n" +
	"\x0epayment_method\x18\x03 \x01(\x0e2\x18.ecommerce.PaymantMethodR\rpaymentMethod\x12)\n" +
	"\x10shipping_address\x18\x04 \x01(\tR\x0fshippingAddress\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"M\n" +
	"\x10OrderItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xac\x01\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x05R\x0ediscountAmount\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.ecommerce.OrderStatusR\x06status\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\":\n" +
	"\x10GetOrderResponse\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.ecommerce.OrderR\x05order\"l\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x125\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x16.ecommerce.OrderStatusR\tnewStatus\"]\n" +
	"\x19UpdateOrderStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05order\x18\x02 \x01(\v2\x10.ecommerce.OrderR\x05order\"\x95\x01\n" +
	"\x11ListOrdersRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.ecommerce.OrderStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x94\x01\n" +
	"\x12ListOrdersResponse\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.ecommerce.OrderR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"w\n" +
	"\x0eSupportMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*m\n" +
	"\vOrderStatus\x12\x11\n" +
	"\rORDER_PENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"ORDER_PAID\x10\x01\x12\x11\n" +
	"\rORDER_SHIPPED\x10\x02\x12\x13\n" +
	"\x0fORDER_DELIVERED\x10\x03\x12\x13\n" +
	"\x0fORDER_CANCELLED\x10\x04*V\n" +
	"\rPaymantMethod\x12\x17\n" +
	"\x13PAYMENT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPAYMENT_CARD\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_BANK_TRANCSFER\x10\x022\xea\x03\n" +
	"\fOrderService\x12L\n" +
	"\vCreateOrder\x12\x1d.ecommerce.CreateOrderRequest\x1a\x1e.ecommerce.CreateOrderResponse\x12C\n" +
	"\bGetOrder\x12\x1a.ecommerce.GetOrderRequest\x1a\x1b.ecommerce.GetOrderResponse\x12^\n" +
	"\x11UpdateOrderStatus\x12#.ecommerce.UpdateOrderStatusRequest\x1a$.ecommerce.UpdateOrderStatusResponse\x12D\n" +
	"\x12StreamOrderUpdates\x12\x1a.ecommerce.GetOrderRequest\x1a\x10.ecommerce.Order0\x01\x12S\n" +
	"\x10BulkCreateOrders\x12\x1d.ecommerce.CreateOrderRequest\x1a\x1e.ecommerce.CreateOrderResponse(\x01\x12L\n" +
	"\x10ChatOrderSupport\x12\x19.ecommerce.SupportMessage\x1a\x19.ecommerce.SupportMessage(\x010\x01B1Z/github.com/Egot3/microservicesTest/apiContractsb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_order_proto_goTypes = []any{
	(OrderStatus)(0),                  // 0: ecommerce.OrderStatus
	(PaymantMethod)(0),                // 1: ecommerce.PaymantMethod
	(*Discount)(nil),                  // 2: ecommerce.Discount
	(*PercentDiscount)(nil),           // 3: ecommerce.PercentDiscount
	(*FixedAmountDiscount)(nil),       // 4: ecommerce.FixedAmountDiscount
	(*OrderItem)(nil),                 // 5: ecommerce.OrderItem
	(*Order)(nil),                     // 6: ecommerce.Order
	(*CreateOrderRequest)(nil),        // 7: ecommerce.CreateOrderRequest
	(*OrderItemRequest)(nil),          // 8: ecommerce.OrderItemRequest
	(*CreateOrderResponse)(nil),       // 9: ecommerce.CreateOrderResponse
	(*GetOrderRequest)(nil),           // 10: ecommerce.GetOrderRequest
	(*GetOrderResponse)(nil),          // 11: ecommerce.GetOrderResponse
	(*UpdateOrderStatusRequest)(nil),  // 12: ecommerce.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil), // 13: ecommerce.UpdateOrderStatusResponse
	(*ListOrdersRequest)(nil),         // 14: ecommerce.ListOrdersRequest
	(*ListOrdersResponse)(nil),        // 15: ecommerce.ListOrdersResponse
	(*SupportMessage)(nil),            // 16: ecommerce.SupportMessage
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	3,  // 0: ecommerce.Discount.percent:type_name -> ecommerce.PercentDiscount
	4,  // 1: ecommerce.Discount.fixed:type_name -> ecommerce.FixedAmountDiscount
	2,  // 2: ecommerce.OrderItem.item_discount:type_name -> ecommerce.Discount
	5,  // 3: ecommerce.Order.items:type_name -> ecommerce.OrderItem
	0,  // 4: ecommerce.Order.status:type_name -> ecommerce.OrderStatus
	1,  // 5: ecommerce.Order.payment_method:type_name -> ecommerce.PaymantMethod
	2,  // 6: ecommerce.Order.order_discount:type_name -> ecommerce.Discount
	17, // 7: ecommerce.Order.created_at:type_name -> google.protobuf.Timestamp
	17, // 8: ecommerce.Order.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 9: ecommerce.CreateOrderRequest.items:type_name -> ecommerce.OrderItemRequest
	1,  // 10: ecommerce.CreateOrderRequest.payment_method:type_name -> ecommerce.PaymantMethod
	0,  // 11: ecommerce.CreateOrderResponse.status:type_name -> ecommerce.OrderStatus
	6,  // 12: ecommerce.GetOrderResponse.order:type_name -> ecommerce.Order
	0,  // 13: ecommerce.UpdateOrderStatusRequest.new_status:type_name -> ecommerce.OrderStatus
	6,  // 14: ecommerce.UpdateOrderStatusResponse.order:type_name -> ecommerce.Order
	0,  // 15: ecommerce.ListOrdersRequest.status:type_name -> ecommerce.OrderStatus
	6,  // 16: ecommerce.ListOrdersResponse.orders:type_name -> ecommerce.Order
	17, // 17: ecommerce.SupportMessage.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 18: ecommerce.OrderService.CreateOrder:input_type -> ecommerce.CreateOrderRequest
	10, // 19: ecommerce.OrderService.GetOrder:input_type -> ecommerce.GetOrderRequest
	12, // 20: ecommerce.OrderService.UpdateOrderStatus:input_type -> ecommerce.UpdateOrderStatusRequest
	10, // 21: ecommerce.OrderService.StreamOrderUpdates:input_type -> ecommerce.GetOrderRequest
	7,  // 22: ecommerce.OrderService.BulkCreateOrders:input_type -> ecommerce.CreateOrderRequest
	16, // 23: ecommerce.OrderService.ChatOrderSupport:input_type -> ecommerce.SupportMessage
	9,  // 24: ecommerce.OrderService.CreateOrder:output_type -> ecommerce.CreateOrderResponse
	11, // 25: ecommerce.OrderService.GetOrder:output_type -> ecommerce.GetOrderResponse
	13, // 26: ecommerce.OrderService.UpdateOrderStatus:output_type -> ecommerce.UpdateOrderStatusResponse
	6,  // 27: ecommerce.OrderService.StreamOrderUpdates:output_type -> ecommerce.Order
	9,  // 28: ecommerce.OrderService.BulkCreateOrders:output_type -> ecommerce.CreateOrderResponse
	16, // 29: ecommerce.OrderService.ChatOrderSupport:output_type -> ecommerce.SupportMessage
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_order_proto_msgTypes[0].OneofWrappers = []any{
		(*Discount_Percent)(nil),
		(*Discount_Fixed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
